server:
  port: 8080
spring:
  application:
    name: "parqueadero"
  devtools:
    add-properties: false
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://admin2:QtC5e4bxxw!tJJL@cluster0.pqco8.mongodb.net/db_parqueadero?retryWrites=true&w=majority"

