//Add(Create)
export const ADD_FACTURA = 'ADD_FACTURA';
export const ADD_FACTURA_SUCCESS = 'ADD_FACTURA_SUCCESS';
export const ADD_FACTURA_FAILURE = 'ADD_FACTURA_FAILURE';

//List(Read)
export const LIST_FACTURAS = 'LIST_FACTURAS';
export const LIST_FACTURAS_SUCCESS = 'LIST_FACTURAS_SUCCESS';
export const LIST_FACTURAS_FAILURE = 'LIST_FACTURAS_FAILURE';

//Delete
export const DELETE_FACTURA = 'DELETE_FACTURA';
export const DELETE_FACTURA_SUCCESS = 'DELETE_FACTURA_SUCCESS';
export const DELETE_FACTURA_FAILURE = 'DELETE_FACTURA_FAILURE';

//Ver(Read)
export const ONLY_FACTURA = 'ONLY_FACTURA';

//Edit
export const EDIT_FACTURA = 'EDIT_FACTURA';