//Add(Create)
export const ADD_TICKET = 'ADD_TICKET';
export const ADD_TICKET_SUCCESS = 'ADD_TICKET_SUCCESS';
export const ADD_TICKET_FAILURE = 'ADD_TICKET_FAILURE';

//List(Read)
export const LIST_TICKETS = 'LIST_TICKETS';
export const LIST_CELDAS = 'LIST_CELDAS';
export const LIST_CELDAS_SUCCESS = 'LIST_TICKETS_SUCCESS';
export const LIST_TICKETS_SUCCESS = 'LIST_TICKETS_SUCCESS';
export const LIST_CELDAS_FAILURE = 'LIST_TICKETS_FAILURE';
export const LIST_TICKETS_FAILURE = 'LIST_TICKETS_FAILURE';

//Delete
export const DELETE_TICKET = 'DELETE_TICKET';
export const DELETE_TICKET_SUCCESS = 'DELETE_TICKET_SUCCESS';
export const DELETE_TICKET_FAILURE = 'DELETE_TICKET_FAILURE';

//Ver(Read)
export const ONLY_TICKET = 'ONLY_TICKET';
export const OBTENER_TICKET = 'OBTENER_TICKET';

//Edit
export const EDIT_TICKET = 'EDIT_TICKET';